### ISSUE TITLE
Sometimes the `stats.ts` script in `smart-contracts` exits with an error

### ISSUE THREAD

**Issue by kvakes** [windingtree/stays#159] opened 2022-04-16 19:39 UTC
This script is, of course, just a nice-to-have, but I wonder if this is a symptom of a larger issue, e.g. availability of the GNO node we're using...

Error:

```
Error: missing revert data in call exception (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"error\":{\"code\":-32015,\"data\":\"Reverted 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294552433732313a206f776e657220717565727920666f72206e6f6e6578697374656e7420746f6b656e0000000000000000000000000000000000000000000000\",\"message\":\"VM execution error.\"},\"id\":72,\"jsonrpc\":\"2.0\"}","error":{"code":-32015,"data":"Reverted 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294552433732313a206f776e657220717565727920666f72206e6f6e6578697374656e7420746f6b656e0000000000000000000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xecff1da7acd4025c532c04db3b57b454bab95b4e\",\"data\":\"0x6352211e0000000000000000000000000000000000000000000000000000000000000007\"},\"latest\"],\"id\":72,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://poa-xdai.gateway.pokt.network/v1/lb/6255d2a0adb03f003800758d"}, data="0x", code=CALL_EXCEPTION, version=providers/5.5.3)
    at Logger.makeError (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at checkError (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:34:16)
    at JsonRpcProvider.<anonymous> (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:562:20)
    at step (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'missing revert data in call exception',
  code: 'CALL_EXCEPTION',
  error: Error: processing response error (body="{\"error\":{\"code\":-32015,\"data\":\"Reverted 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294552433732313a206f776e657220717565727920666f72206e6f6e6578697374656e7420746f6b656e0000000000000000000000000000000000000000000000\",\"message\":\"VM execution error.\"},\"id\":72,\"jsonrpc\":\"2.0\"}", error={"code":-32015,"data":"Reverted 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294552433732313a206f776e657220717565727920666f72206e6f6e6578697374656e7420746f6b656e0000000000000000000000000000000000000000000000"}, requestBody="{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xecff1da7acd4025c532c04db3b57b454bab95b4e\",\"data\":\"0x6352211e0000000000000000000000000000000000000000000000000000000000000007\"},\"latest\"],\"id\":72,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://poa-xdai.gateway.pokt.network/v1/lb/6255d2a0adb03f003800758d", code=SERVER_ERROR, version=web/5.5.1)
      at Logger.makeError (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
      at Logger.throwError (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
      at /home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/web/src.ts/index.ts:321:28
      at step (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"error":{"code":-32015,"data":"Reverted 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294552433732313a206f776e657220717565727920666f72206e6f6e6578697374656e7420746f6b656e0000000000000000000000000000000000000000000000","message":"VM execution error."},"id":72,"jsonrpc":"2.0"}',
    error: Error: VM execution error.
        at getResult (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:97:28)
        at processJsonFunc (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/web/src.ts/index.ts:363:22)
        at /home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/web/src.ts/index.ts:300:42
        at step (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/home/kvakes/Projects/stays/packages/smart-contracts/node_modules/@ethersproject/web/lib/index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      code: -32015,
      data: 'Reverted 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294552433732313a206f776e657220717565727920666f72206e6f6e6578697374656e7420746f6b656e0000000000000000000000000000000000000000000000'
    },
    requestBody: '{"method":"eth_call","params":[{"to":"0xecff1da7acd4025c532c04db3b57b454bab95b4e","data":"0x6352211e0000000000000000000000000000000000000000000000000000000000000007"},"latest"],"id":72,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'https://poa-xdai.gateway.pokt.network/v1/lb/6255d2a0adb03f003800758d'
  },
  data: '0x'
}
```

**Comment by valera-rozuvan** [comment] 2022-04-19 09:47
Could not reproduce.

**Comment by AntNezh** [comment] 2022-04-19 11:35
Could not reproduce. May be was fixed

**Comment by valera-rozuvan** [comment] 2022-04-20 07:11
Closing this.

**Closed as completed by valera-rozuvan** 2022-04-20 07:11 UTC
Labels: bug
