### ISSUE TITLE
Uploading facility images is not working

### ISSUE THREAD

**Issue by kvakes** [windingtree/stays#73] opened 2022-04-12 18:40 UTC
I was able to upload facility logo, but then while trying to upload multiple "facility images" (they are called "room images" for some reason on the facility page), I get this error:

`FacilityProfileCard: Error: Cannot connect to the source: https://api.web3.storage/upload`

**Comment by valera-rozuvan** [comment] 2022-04-14 08:36
Will try to reproduce, and fix if still an issue.

**Comment by valera-rozuvan** [comment] 2022-04-19 09:47
Could not reproduce.

**Comment by AntNezh** [comment] 2022-04-19 11:11
Could not reproduce.

**Comment by valera-rozuvan** [comment] 2022-04-20 07:10
Closing this.

**Closed as completed by valera-rozuvan** 2022-04-20 07:10 UTC
Labels: bug
