### ISSUE TITLE
Sometimes Hilton doesn't show up. It happened to me and to Garry_Moonlover

### ISSUE THREAD

**Issue by kvakes** [windingtree/stays#110] opened 2022-04-14 07:08 UTC
![Screenshot from 2022-04-14 09-07-59](https://user-images.githubusercontent.com/377005/163332662-21ff2511-f6ab-4d28-aaea-4e29bcd3e6cb.png)

**Comment by valera-rozuvan** [comment] 2022-04-19 09:47
Could not reproduce.

**Comment by AntNezh** [comment] 2022-04-19 11:33
Could not reproduce. May be was fixed

**Comment by valera-rozuvan** [comment] 2022-04-20 07:09
Closing this.

**Closed as completed by valera-rozuvan** 2022-04-20 07:09 UTC
Labels: bug
