### ISSUE TITLE
Dapp shows an incorrect "nothing found" error when loading rooms

### ISSUE THREAD

**Issue by kvakes** [windingtree/stays#106] opened 2022-04-13 16:47 UTC
Video of the problem: https://youtu.be/_xbMy2DY8E4

**Comment by valera-rozuvan** [comment] 2022-04-19 09:47
Could not reproduce.

**Comment by AntNezh** [comment] 2022-04-19 11:27
Could not reproduce. May be was fixed already.

**Comment by valera-rozuvan** [comment] 2022-04-20 07:10
Closing this.

**Closed as completed by valera-rozuvan** 2022-04-20 07:10 UTC
Labels: bug
